### ISSUE TITLE
Don't work with pygame 1.8.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chubakur/wizards-magic2#7]
```
Debian Squeeze, WizardsMagic-2.3.15

On click "StartGame" application crashed with:
  AttributeError: 'pygame.Rect' object has no attribute 'copy'

pygame.Rect.coopy present in pygame 1.9.1 but not in pygame 1.8.1


Fix in attached patch.
```

Original issue reported on code.google.com by `neo.nix....@gmail.com` on 26 Jun 2011 at 8:26

Attachments:
- [wizard.patch](https://storage.googleapis.com/google-code-attachments/wizards-magic/issue-7/comment-0/wizard.patch)
